name: SSH

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'true'
jobs:
  build:
    runs-on: ubuntu-latest   
    permissions:
      actions: write
      contents: write
    steps:
    - name: 准备完成
      uses: actions/checkout@main
      
    - name: 运行       
      run: | 
          wget https://github.com/multiarch/qemu-user-static/releases/download/v5.1.0-2/qemu-aarch64-static.tar.gz
          
          tar -zxvf qemu-aarch64-static.tar.gz
          sudo cp qemu-aarch64-static /usr/bin/
          chmod +x /usr/bin/qemu-aarch64-static

          docker run --rm --privileged multiarch/qemu-user-static:register --reset

          docker run -t -v /usr/bin/qemu-aarch64-static:/usr/bin/qemu-aarch64-static arm64v8/ubuntu:20.04 uname -m
 

          #cd ./node-app/
            
            # docker build -t node-app .
            # docker save -o ../images/image.tar node-app

    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        
    - name: 自动发布固件到 Releases
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: FastRhino-R66S-linux-固件下载
        tag_name: aaaaaaaa
        files: ./images/* 
